Repository MLSysOps/MLE-agent, pull requests merged in 2024-11, with the labels that each got.

#230 [MRG] add gemini model
  mle/agents/coder.py
  mle/cli.py
  mle/function/search.py
  mle/model/__init__.py
  mle/model/gemini.py
Labels: enhancement, size:L, lgtm

#263 [MRG] Update README.md with a typo fix
  README.md
Labels: documentation, size:XS, lgtm

#262 [MRG] add lancedb as memory
  mle/cli.py
  mle/utils/memory.py
  requirements.txt
Labels: enhancement, size:L, lgtm

#265 [MRG] Code RAG for Chatbot
  mle/agents/chat.py
  mle/cli.py
  mle/utils/__init__.py
  mle/utils/chunk.py
  mle/utils/data.py
  mle/utils/memory.py
  mle/utils/parser.py
  mle/utils/system.py
  mle/workflow/__init__.py
  mle/workflow/chat.py
  mle/workflow/report.py
  mle/workflow/report_local.py
  requirements.txt
Labels: size:XL

#269 [MRG] clean chromadb and add manage api for lancedb memory
  mle/utils/memory.py
  requirements.txt
Labels: enhancement, size:L, lgtm

#274 [MRG] Fixed the memory init before config error
  mle/cli.py
  requirements.txt
Labels: size:XS, Bug fix
