Repository MLSysOps/MLE-agent, pull requests merged in 2024-10, with the labels that each got.

#228 [MRG] Added the local .git metadata fetchers
  mle/integration/__init__.py
  mle/integration/local_git.py
  requirements.txt
Labels: enhancement, size:L, lgtm

#233 [MRG] update readme
  README.md
Labels: documentation, size:XS, lgtm

#235 [MRG] 🐛 fix: removed the pr agent
  .github/workflows/pr_agent.yml
Labels: size:S, lgtm, Bug fix

#236 [MRG] Update README.md
  README.md
Labels: documentation, size:XS, lgtm

#238 [MRG] Update README.md
  README.md
Labels: documentation, size:XS, lgtm

#237 [MRG] Fixed bugs of Kaggle integration
  mle/agents/advisor.py
  mle/agents/coder.py
  mle/agents/debugger.py
  mle/agents/summarizer.py
  mle/cli.py
  mle/integration/__init__.py
  mle/integration/kaggle.py
  mle/utils/data.py
  mle/workflow/__init__.py
  mle/workflow/kaggle.py
  mle/workflow/report.py
  requirements.txt
Labels: size:L, lgtm, Bug fix

#239 [MRG] Update the advisor to support various modes
  mle/agents/advisor.py
  mle/agents/summarizer.py
  mle/workflow/kaggle.py
Labels: enhancement, size:M, lgtm

#241 [MRG] Built version v0.4.2
  mle/version.py
Labels: size:XS, lgtm

#242 [MRG] Updated the readme with v0.4.2
  README.md
Labels: documentation, size:L, lgtm

#243 [MRG] Update README.md -- fixed a typo for the kaggle CLI
  README.md
Labels: documentation, size:XS, lgtm

#246 [MRG] Support different modality dataset; add debug max attempt limit
  mle/agents/advisor.py
  mle/cli.py
  mle/workflow/kaggle.py
Labels: enhancement, size:S, lgtm

#248 [MRG] quickfix: miss list_files function
  mle/agents/advisor.py
Labels: size:XS, lgtm

#249 [MRG] update the preview_csv_data function
  mle/function/data.py
Labels: enhancement, size:M, lgtm

#252 [MRG] enhance `list_files` function
  mle/function/files.py
Labels: enhancement, size:M, lgtm

#253 [MRG] Improve data operation functions
  mle/agents/coder.py
  mle/function/__init__.py
  mle/function/data.py
  mle/function/execution.py
  mle/function/files.py
Labels: enhancement, size:L, lgtm

#256 [MRG] quickfix: missing imports and some bugs
  mle/integration/kaggle.py
  requirements.txt
Labels: size:S, lgtm, Bug fix

#245 [MRG] Add a command to generate report for local git repository
  README.md
  mle/agents/summarizer.py
  mle/cli.py
  mle/integration/local_git.py
  mle/workflow/__init__.py
  mle/workflow/kaggle.py
  mle/workflow/report.py
  mle/workflow/report_local.py
Labels: documentation, enhancement, size:L, lgtm

#258 [MRG][NIT] Add missing parameter in comment
  mle/agents/summarizer.py
  mle/workflow/report_local.py
Labels: documentation, size:XS, lgtm
