Repository MLSysOps/MLE-agent, pull requests merged in 2024-08, with the labels that each got.

#123 [MRG] add previous step&task resume
  mle/utils/__init__.py
  mle/utils/cache.py
  mle/utils/system.py
  mle/workflow/baseline.py
Labels: enhancement, size:L, lgtm

#124 [MRG] 👷 build: 0.3.1
  mle/version.py
Labels: enhancement, size:XS, lgtm, Review effort [1-5]: 1

#125 [MRG] add star history
  README.md
Labels: documentation, size:XS, lgtm, Review effort [1-5]: 1

#132 [MRG] Improve advisor agent with markdown output
  mle/agents/__init__.py
  mle/agents/reporter.py
  mle/cli.py
  mle/utils/system.py
  mle/workflow/__init__.py
  mle/workflow/report.py
Labels: enhancement, size:L, lgtm, Review effort [1-5]: 3

#135 [MRG] Upgrade setuptools
  requirements.txt
Labels: enhancement, size:XS, lgtm, Review effort [1-5]: 1

#137 [MRG] fix typos
  .gitignore
  mle/workflow/baseline.py
Labels: enhancement, size:S, lgtm, Review effort [1-5]: 2

#138 Update
  mle/agents/debugger.py
  mle/agents/planner.py
  mle/agents/reporter.py
Labels: enhancement, size:M, lgtm

#141 update
  mle/utils/cache.py
  mle/utils/system.py
Labels: size:M, lgtm

#142 [MRG] Enrich the github apis
  mle/integration/github.py
Labels: enhancement, size:M, lgtm

#136 [MRG] Add RAG for the code analysis
  mle/cli.py
  mle/utils/__init__.py
  mle/utils/memory.py
  requirements.txt
Labels: enhancement, size:L, Review effort [1-5]: 3, dependencies

#149 [MRG] add google calender integration
  mle/integration/__init__.py
  mle/integration/google_calendar.py
  requirements.txt
Labels: enhancement, size:L, lgtm, Review effort [1-5]: 3

#151 [MRG] github & google calendar integrate command
  mle/cli.py
  mle/integration/github.py
  mle/integration/google_calendar.py
  mle/utils/system.py
  mle/workflow/report.py
Labels: enhancement, size:L, lgtm

#152 [MRG] update readme
  README.md
Labels: documentation, size:S, lgtm, Review effort [1-5]: 1
