Repository MLSysOps/MLE-agent, pull requests merged in 2024-09, with the labels that each got.

#156 docs: update google_calendar.py
  mle/integration/google_calendar.py
Labels: documentation, size:XS, lgtm

#157 [MRG] fix typos
  mle/workflow/baseline.py
Labels: size:XS, lgtm

#154 [MRG] add claude model support
  mle/cli.py
  mle/model.py
  mle/workflow/baseline.py
  mle/workflow/kaggle.py
  mle/workflow/report.py
Labels: enhancement, size:L, lgtm

#161 [MRG] finish some tasks in README and improve requirement
  README.md
  requirements.txt
Labels: documentation, enhancement, size:XS, lgtm, Review effort [1-5]: 1

#163 [MRG] Add web documentation framework
  .github/workflows/deploy_docs.yml
  docs/.gitignore
  docs/components/counters.module.css
  docs/components/counters.tsx
  docs/next-env.d.ts
  docs/next.config.js
  docs/package.json
  docs/pages/_meta.json
  docs/pages/about.mdx
  docs/pages/examples.mdx
  docs/pages/examples/image_classification.mdx
  docs/pages/index.mdx
  docs/pages/start.mdx
  docs/pnpm-lock.yaml
  docs/theme.config.tsx
  docs/tsconfig.json
Labels: documentation, enhancement, size:L, lgtm, Review effort [1-5]: 3

#147 [MRG] added the summary agent
  mle/agents/summarizer.py
  mle/cli.py
  mle/function/__init__.py
  mle/function/search.py
  mle/integration/github.py
  mle/model.py
  mle/workflow/__init__.py
  mle/workflow/kaggle.py
  mle/workflow/report.py
Labels: enhancement, size:XL, lgtm, Review effort [1-5]: 3

#168 [MRG] Adding trending badge to README.md
  README.md
Labels: documentation, size:XS, lgtm, Review effort [1-5]: 1

#167 [MRG] support `mle report <org/repo>` command
  mle/cli.py
  mle/workflow/report.py
Labels: enhancement, size:L, lgtm

#171 [MRG] Implementation the initial report agent
  mle/agents/reporter.py
  mle/agents/summarizer.py
  mle/cli.py
  mle/integration/github.py
  mle/integration/google_calendar.py
  mle/utils/system.py
  mle/workflow/report.py
Labels: enhancement, size:XL, lgtm, Bug fix, Review effort [1-5]: 4

#172 Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, size:XS, lgtm

#170 [MRG] fix: generate no code
  mle/agents/coder.py
  mle/agents/debugger.py
  mle/model.py
Labels: bug, size:M, lgtm

#175 [MRG] updated the docs of contributing
  CONTRIBUTING.md
  mle/workflow/report.py
Labels: documentation, size:M, lgtm, Review effort [1-5]: 2

#177 [MRG] the local web server to display the MLE suggestions
  mle/agents/reporter.py
  mle/cli.py
  mle/server/__init__.py
  mle/server/app.py
  mle/workflow/report.py
  requirements.txt
  web/.eslintrc.json
  web/.gitignore
  web/README.md
  web/app/favicon.ico
  web/app/fonts/GeistMonoVF.woff
  web/app/fonts/GeistVF.woff
  web/app/globals.css
  web/app/layout.tsx
  web/app/page.tsx
  web/next.config.mjs
  web/package-lock.json
  web/package.json
  web/pnpm-lock.yaml
  web/postcss.config.mjs
  web/tailwind.config.ts
  web/tsconfig.json
Labels: enhancement, size:XL, lgtm, Review effort [1-5]: 2, dependencies

#179 [MRG] Improve the web UI to use the sync backend API
  mle/agents/reporter.py
  mle/agents/summarizer.py
  mle/cli.py
  mle/server/app.py
  mle/workflow/report.py
  web/app/page.tsx
  web/package.json
  web/pnpm-lock.yaml
Labels: enhancement, size:L, lgtm, Review effort [1-5]: 3, Bug fix

#183 [MRG] Fixed the UI bug of no report generation
  mle/agents/reporter.py
  web/app/page.tsx
Labels: enhancement, size:S, lgtm, Review effort [1-5]: 2, Bug fix

#187 [MRG] suggest datasets if user's input is unclear
  mle/agents/advisor.py
  mle/utils/system.py
  mle/workflow/baseline.py
Labels: enhancement, size:M, lgtm

#184 [MRG] combile pnpm dev and mle serve within `mle report`
  MANIFEST.in
  mle/cli.py
  mle/utils/system.py
Labels: size:L, lgtm

#190 [MRG] fix prevewing public dataset errors
  mle/agents/advisor.py
  mle/cli.py
Labels: bug, enhancement, size:XS, lgtm, Review effort [1-5]: 2, Bug fix

#186 [MRG] move config file into `.mle`
  mle/cli.py
  mle/model.py
  mle/utils/memory.py
  mle/utils/system.py
  mle/workflow/report.py
Labels: size:M, lgtm

#191 [MRG] add `mle kaggle` pipeline
  mle/cli.py
  mle/function/data.py
  mle/integration/__init__.py
  mle/integration/kaggle.py
  mle/model.py
  mle/workflow/__init__.py
  mle/workflow/kaggle.py
Labels: enhancement, size:L, lgtm

#198 [MRG] fix ollama output without json format
  mle/model.py
Labels: bug, size:XS, lgtm

#185 [MRG] add github setting to the web
  mle/server/app.py
  mle/workflow/report.py
  web/app/page.tsx
  web/public/favicon.ico
  web/public/logo.png
Labels: size:M, lgtm

#201 [MRG] fix UI icons
  web/app/page.tsx
Labels: bug, enhancement, size:XS, lgtm, Review effort [1-5]: 2

#192 [MRG] Add mistralai support
  mle/agents/advisor.py
  mle/agents/planner.py
  mle/cli.py
  mle/model.py
  mle/utils/__init__.py
  mle/utils/data.py
Labels: bug, enhancement, size:L, lgtm

#204 [MRG] fix: display report UI after finish the static resouces loading
  web/app/layout.tsx
Labels: size:S, lgtm, Bug fix

#208 [MRG] build version v0.4.0
  mle/version.py
Labels: enhancement, size:XS, lgtm, Review effort [1-5]: 1

#209 [MRG] update readme for 0.4.0
  README.md
Labels: documentation, size:XS, Review effort [1-5]: 1

#212 [MRG] deepseek support
  mle/cli.py
  mle/model.py
Labels: enhancement, size:L, lgtm

#213 [MRG] add kaggle requirement summary
  mle/agents/summarizer.py
  mle/workflow/kaggle.py
Labels: enhancement, size:M, lgtm

#214 [MRG] add langfuse
  mle/model.py
  mle/utils/data.py
  mle/utils/system.py
  requirements.txt
Labels: enhancement, size:L, lgtm

#215 [MRG] update README.md with kaggle and report mode
  README.md
Labels: documentation, size:M, lgtm

#217 [MRG] add manual openai base_url
  mle/model.py
Labels: enhancement, size:XS, lgtm

#219 [MRG] update web ui icon
  web/public/logo.png
Labels: size:XS, lgtm

#218 [MRG] inject the project info into chat system prompt
  mle/cli.py
  mle/utils/cache.py
Labels: enhancement, size:M, lgtm

#221 [MRG] add check for config file
  mle/utils/system.py
Labels: size:S, lgtm

#223 [MRG] update README.md
  README.md
Labels: documentation, size:S, lgtm

#224 [MRG] redesign `mle chat`
  mle/agents/__init__.py
  mle/agents/chat.py
  mle/agents/coder.py
  mle/cli.py
  mle/utils/cache.py
  mle/workflow/__init__.py
  mle/workflow/baseline.py
  mle/workflow/chat.py
  mle/workflow/kaggle.py
Labels: enhancement, size:L, lgtm

#225 [MRG] fix github integration to fetch `master` branch
  mle/integration/github.py
Labels: bug, size:XS, lgtm
