Repository MLSysOps/MLE-agent, pull requests merged in 2024-07, with the labels that each got.

#116 [MRG] Create pr_agent.yml
  .github/workflows/pr_agent.yml
Labels: size:S, lgtm

#117 [MRG] refactor the displayed info, fix small UI issues
  README.md
  mle/agents/advisor.py
  mle/agents/coder.py
  mle/agents/planner.py
  mle/workflow/baseline.py
Labels: enhancement, size:M, lgtm, Review effort [1-5]: 2

#118 add new video
  README.md
Labels: documentation, size:XS, lgtm, Review effort [1-5]: 1

#119 Update README.md for v030
  README.md
Labels: documentation, size:M, lgtm, Review effort [1-5]: 1

#120 [MRG] build version v0.3.0
  mle/version.py
Labels: enhancement, size:XS, lgtm, Review effort [1-5]: 1
