Repository MLSysOps/MLE-agent, pull requests merged in 2025-04, with the labels that each got.

#290 [MRG] Add vLLM backend support, currently tested Mistral-7B-Instruct-…
  mle/cli.py
  mle/model/__init__.py
  mle/model/vllm.py
Labels: enhancement, size:L, lgtm

#291 [MRG] 🚑 quickfix: fixed the lint issues
  mle/cli.py
  mle/model/__init__.py
  mle/model/vllm.py
Labels: size:M, lgtm

#293 Add citation
  .github/workflows/lint.yml
  .github/workflows/test.yml
  README.md
Labels: documentation, size:S, lgtm
