Repository MLSysOps/MLE-agent, pull requests merged in 2025-07, with the labels that each got.

#304 [MRG] Fixed the installation issue
  pyproject.toml
Labels: size:XS, Bug fix

#306 [MRG] Added the dependency for pyproject.toml
  pyproject.toml
Labels: size:XS

#307 [MRG] 🚑 quickfix: fixed the dependency versioning
  pyproject.toml
Labels: size:XS

#310 [MRG] add mem0 memory
  mle/utils/memory.py
  pyproject.toml
Labels: enhancement, size:M

#309 [MRG] feat(model): Update gemini.py to use new Gemini API
  mle/agents/advisor.py
  mle/agents/debugger.py
  mle/model/gemini.py
Labels: enhancement, size:L, lgtm

#311 [MRG] add hybrid memory for long-term and fast retrieval memory
  mle/utils/memory.py
Labels: enhancement, size:L

#318 [MRG] 🐛 use qwen 1.5b as the vllm testing bed
  mle/cli.py
  mle/model/__init__.py
  mle/model/vllm.py
Labels: size:L, Bug fix

#320 [MRG] :bento: [deps] Clean CLI for exp command
  exp/README.md
  exp/cli.py
  mle/cli.py
  pyproject.toml
  uv.lock
Labels: documentation, enhancement, size:M
